app/main/models/pitches.py
class Pitch:

    all_pitches = []

    def __init__(self,pitch):
        self.pitch


    def save_pitch(self):
        Pitch.all_pitches.append(self)


    @classmethod
    def clear_pitches(cls):
        Pitch.all_pitches.clear()


    @classmethod
    def get_pitches(cls,id):

        response = []

        for pitch in cls.all_pitches:
            response.append(pitch)
            
            return response     

app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'pitches',lazy = "dynamic")
    comments = db.relationship('Comment',backref='comments',lazy="dynamic")



    @property  
    def password(self): 
        raise AttributeError('You cannot read the password attribute') 


    @password.setter 
    def password(self, password):   
        self.pass_secure = generate_password_hash(password)   

    def verify_password(self,password):   
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'


class Pitch(UserMixin,db.Model):

    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key=True)
    post = db.Column(db.String(255))
    body = db.Column(db.String(1000))
    category = db.Column(db.String(1000))
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref = 'pitch',lazy = "dynamic")

    
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

class Comment(UserMixin,db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    poster = db.Column(db.String(255))
    comment = db.Column(db.String(1000))
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    pitch_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()        

   

        

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required


class PitchForm(FlaskForm):

    post = StringField('Your name',validators=[Required()])

    body = TextAreaField('Pitch')

    category = SelectField('Pick Category',
                          choices=[('PRODUCT', 'PRODUCT'),
                                ('INTERVIEW', 'INTERVIEW'),
                                ('PICK-UP', 'PICK-UP'),
                                   ('PROMOTION', 'PROMOTION')],
                          validators=[Required()])
   
    submit = SubmitField('Pitch')

class CommentForm(FlaskForm):

    poster = StringField('Your name',validators=[Required()])

    comment = TextAreaField('Your comment',validators=[Required()])
    
    submit = SubmitField('Comment')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask import Blueprint
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config_options
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

# Initializing application
def create_app(config_name):
    app = Flask(__name__)


        # Creating the app configurations
    app.config.from_object(config_options[config_name])

# configure UploadSet
    configure_uploads(app,photos)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint 
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    #setting config
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,forms,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import PitchForm,CommentForm
from flask_login import login_required, current_user
from .. import auth
from ..models import User,Pitch,Comment
from .forms import UpdateProfile
from .. import db,photos



#views
@main.route('/')
def index():
    '''
    View root page function that returns index page and its data
    '''
    title = 'PITCH PERFECT'

    index=Pitch.query.all()

    return render_template('index.html', title = title, index = index)   

@main.route('/new_pitch', methods = ['GET','POST'])
@login_required
def new_pitch():   
    form = PitchForm() 
    if form.validate_on_submit():
        pitch = Pitch(post=form.post.data,body=form.body.data,category=form.category.data)
        pitch.save_pitch()
        return redirect(url_for('main.index'))
    return render_template('new_pitch.html',form=form) 

@main.route('/product', methods = ['GET','POST'])

def product():

    product_pitches=Pitch.query.filter_by(category="PRODUCT")

    

    return render_template('product.html', product_pitches = product_pitches )

@main.route('/interview', methods = ['GET','POST'])

def interview():

    interview_pitches=Pitch.query.filter_by(category="INTERVIEW")
   
    return render_template('interview.html', interview_pitches = interview_pitches)    



@main.route('/promotion', methods = ['GET','POST'])

def promotion():

    promotion_pitches=Pitch.query.filter_by(category="PROMOTION")
   
    return render_template('promotion.html', promotion_pitches = promotion_pitches)

@main.route('/pitch', methods = ['GET','POST'])

def pitch():

    pitches_interview=Pitch.query.filter_by(category="PICK-UP")
   
    return render_template('pitch.html',pitches_interview=pitches_interview)




@main.route('/comment/<int:id>', methods = ['GET','POST'])
@login_required
def new_comment(id):   
    fom = CommentForm()
    pitch = Pitch.query.get(id)
    if fom.validate_on_submit():
        comment = Comment(poster=fom.poster.data,comment=fom.comment.data, pitch=pitch)
        db.session.add(comment)
        db.session.commit()
    comm = Comment.query.filter_by(pitch=pitch).all()
    return render_template('comment.html',comm=comm,fom=fom)
    

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)



@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{{ wtf.quick_form(form) }}

app/templates/comment.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<div class="container" style="background-color:rgb(245, 245, 155);">
    <div class="row">
        <div class="col-md-3" style="padding:150px;"></div>
        <div class="col-md-6">
            {{ wtf.quick_form(fom) }}
        </div>
     
                {% for comment in comm %}
              
              <p>{{ comment.comment }}</p> 
              <p> By: {{comment.poster}}</p>

                {% endfor %}
        
    </div>
</div>

{% endblock %}

app/templates/fourOwfour.html
{% block content %}
<img src="https://cdn.mos.cms.futurecdn.net/PuXipAW3AXUzUJ4uYyxPKC.jpg" height="600px" width="1360px" alt="">
{% endblock %}

app/templates/index.html
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8"> {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title> PITCH ALONG </title>
    {% endif %}
    <link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Chewy" rel="stylesheet">
</head>
{% extends 'base.html'%} {% import 'macros.html' as macro%}{% import "bootstrap/wtf.html" as wtf %}

<body>
    {% block content %}

    <div class="jumbotron">
        <H1 style="font-family: 'Cookie', cursive; text-align: center; color: #3A005C;">Whats on your mind........Impress
            someone now.</H1>

    </div>
    <div class="container" style="background-color: rgb(235, 230, 160);">
        <h3 style="text-align:center">Choose a category below and pitch or view pitches</h3>
        <nav class="navbar navbar-default" role="navigation" style="text-align:center;">

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse" id="pro">
                <ul class="nav navbar-nav">
                    <li style="padding-right:150px; color:blue;"><a href="/pitch">Pick up</a></li>
                    <li style="padding-right:150px; color:blue;"><a href="/product">Product</a></li>
                    <li style="padding-right:150px; color:blue;"><a href="/interview">Interview</a></li>
                    <li style="padding-right:150px; color:blue;"><a href="/promotion">Promotion</a></li>

                </ul>
            </div>
        </nav>



        {% for prodo in index %}
        <div class="panel panel-success panel-heading" style="text-align:center;">
            <ol>
                <h3>Category: {{prodo.category}}</h3>
                <H3 style="font-family: 'Cookie', cursive;">{{prodo.body}}</H3>
                <p>By:{{prodo.post}}</p>
                <p>{{prodo.date_posted}}</p>
                <a href="/comment/4">comment</a>
              
                <h3>Comments</h3>
           {% for comment in comm %}
           {{comment.poster}}
           By:{{ comment.comment }}

           {% endfor %}

            </ol>
        </div>
        



        {% endfor %}
    </div>

    {% endblock%}
</body>

</html>

app/templates/interview.html
<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">

{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
<div class="row">
        <nav class="navbar navbar-default" role="navigation">
    
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse" id="pro">
                  <ul class="nav navbar-nav">
                    <li><a href="/pitch">Pick up</a></li>
                    <li><a href="/product">Product</a></li>
                  <li><a href="/interview">Interview</a></li>
                    <li><a href="/promotion">Promotion</a></li>
                    
                  </ul>
                </div>
              </nav>
        <h1 class="text-center">Interview-Pitches</h1>
        <hr>

        {% if interview_pitches %}

        {% for pitch in interview_pitches %}           
                <div class="panel panel-success panel-heading">
                        <ol>
                    <H3 style="font-family: 'Cookie', cursive;">{{pitch.body}}</H3> 
                    <p>By:{{pitch.post}}</p>
                    <p>{{pitch.date_posted}}</p> 
                    <a href="/comment">comment</a>
                 
            </div>
                    
                </ol>
                </div>
           
           
        
           {% endfor %}
           
           <a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>

        {% else%}
            <h3 class="text-center">No pitches yet</h3>
            

            <a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>
        {% endif %}

    </div> 





</div>
<h3>Comments</h3>
           <h1>HERE WE GO</h1>
           {% for comment in comm %}
           {{comment.poster}}
           By:{{ comment.comment }}

           {% endfor %}

{% endblock%}

app/templates/macros.html
{% macro displayPitches(pitch_list) %}
    {% for pitch in pitch_list %}
    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 pitch-card">
        
        <p> {{ pitch.pitch | truncate(30) }}</p>
    </div>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<link href="https://fonts.googleapis.com/css?family=Fontdiner+Swanky" rel="stylesheet">


<div class="navbar navbar-inverse" role="navigation" style="background-color: rgb(48, 41, 90);">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                
            </button>             
            <a class="navbar-brand" href="/"><img src="https://static1.squarespace.com/static/58067cd5725e25f7f2f7d64f/t/5a5d20b58165f5ec9d0c636a/1516052677783/Pitch-Logo.png?format=1000w" alt="" style="height:40px; width:80px;"></a>

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li style="font-size:20px;"><a href="/">Home</a></li>

        </div>
        
        <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li style="color:white;padding:18px;font-family: 'Fontdiner Swanky', cursive;"><H3>{{current_user.username}}</H3></li>
                <li class="pro"><a href="{{url_for('main.profile',uname=current_user.username)}}"><H3>profile</H3></a></li>
                <li><a href="{{url_for('auth.logout')}}"><H3>Sign out</H3></a></li>
                {% else %}
                <li><a href="{{url_for('auth.register')}}"><H3>Register</H3></a></li>
                <li><a href="{{url_for('auth.login')}}"><H3>Sign in</H3></a></li>
                {%endif%}
              </ul>



    </div>

</div>

<style>
#pro{
    font-family: 'Cookie', cursive;
    font-size: 30px;
    
}
</style>

app/templates/new_pitch.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<div class="container">
    {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/pitch.html
<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">

{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
<div class="row">
        <nav class="navbar navbar-default" role="navigation">
    
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse" id="pro">
                  <ul class="nav navbar-nav">
                    <li><a href="/pitch">Pick up</a></li>
                    <li><a href="/product">Product</a></li>
                  <li><a href="/interview">Interview</a></li>
                    <li><a href="/promotion">Promotion</a></li>
                    
                  </ul>
                </div>
              </nav>
        <h1 class="text-center">Pick up pitches</h1>
        <hr>

        {% if pitches_interview %}

           {% for pitch in pitches_interview %}
           
                <div class="panel panel-success panel-heading">
                        <ol>
                    <h3 style="font-family: 'Cookie', cursive;">{{pitch.body}}</h3> 
                    <p>By:{{pitch.post}}</p>
                    <p>{{pitch.date_posted}}</p> 
                    
                </ol>
                </div>
           
           
        
           {% endfor %}
           <a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>

        {% else%}
            <h3 class="text-center">No pitches yet</h3>
            

            <a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>
        {% endif %}

    </div> 





</div>

{% endblock%}

app/templates/product.html
<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">

{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
<div class="row">
        <nav class="navbar navbar-default" role="navigation">
    
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse" id="pro">
                  <ul class="nav navbar-nav">
                    <li><a href="/pitch">Pick up</a></li>
                    <li><a href="/product">Product</a></li>
                  <li><a href="/interview">Interview</a></li>
                    <li><a href="/promotion">Promotion</a></li>
                    
                  </ul>
                </div>
              </nav>
        <h1 class="text-center">Product-Pitches</h1>
        <hr>

        {% if product_pitches %}

        {% for prodo in product_pitches %}           
                <div class="panel panel-success panel-heading">
                        <ol>
                    <H3 style="font-family: 'Cookie', cursive;">{{prodo.body}}</H3> 
                    <p>By:{{prodo.post}}</p>
                    <p>{{prodo.date_posted}}</p> 
                    
                </ol>
                </div>
           
           
        
           {% endfor %}
           <a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>

        {% else%}
            <h3 class="text-center">No pitches yet</h3>
            

            <a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>
        {% endif %}

    </div> 





</div>
<style>
#pro{
    font-family: 'Cookie', cursive;
    font-size: 30px;
    color: black;
    
}
</style>
{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  {% if user == current_user %}
  <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

    <input type="file"  name="photo"  required>
    <input type="submit">
  </form>
    {% endif %}
</div>
</div>



{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/promotion.html
<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
<div class="row">
        <nav class="navbar navbar-default" role="navigation">
    
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse" id="pro">
                  <ul class="nav navbar-nav">
                    <li><a href="/pitch">Pick up</a></li>
                    <li><a href="/product">Product</a></li>
                  <li><a href="/interview">Interview</a></li>
                    <li><a href="/promotion">Promotion</a></li>
                    
                  </ul>
                </div>
              </nav>
        <h1 class="text-center">Promotion-Pitches</h1>
        <hr>

        {% if promotion_pitches %}

        {% for pitch in promotion_pitches %}           
                <div class="panel panel-success panel-heading">
                        <ol>
                    <h3 style="font-family: 'Cookie', cursive;">{{pitch.body}}</h3> 
                    <p>By:{{pitch.post}}</p>
                    <p>{{pitch.date_posted}}</p> 
                    
                </ol>
                <h3>Comments</h3>
                {% for comment in comm %}
                By:{{comment.poster}}
                {{ comment.comment }}
     
                {% endfor %}
                </div>
           
           
        
           {% endfor %}
           <a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>

        {% else%}
            <h3 class="text-center">No pitches yet</h3>
            

            <a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>
        {% endif %}

    </div> 




   
</div>
<style>
        #pro{
            font-family: 'Cookie', cursive;
            font-size: 30px;
        }
        </style>

{% endblock%}